<?php

declare(strict_types=1);

namespace Indoctrinate\Service;

use Indoctrinate\Service\Contract\ArtifactWriterInterface;
use PhpParser\BuilderFactory;
use PhpParser\Node;
use PhpParser\PrettyPrinter\Standard;
use Symfony\Component\Console\Style\SymfonyStyle;

final class ArtifactWriter implements ArtifactWriterInterface
{
    /**
     * @param list<string> $sql
     */
    public function writeSqlDump(array $sql, string $path, SymfonyStyle $io): void
    {
        $lines = ['-- Generated by Indoctrinate on ' . date('Y-m-d H:i:s'), ''];

        foreach ($sql as $statement) {
            $lines[] = $statement . ';';
        }

        $lines[] = '';
        file_put_contents($path, implode("\n", $lines));
        $io->success("SQL dump written to: {$path}");
    }

    /**
     * @param list<string> $sql
     */
    public function writeMigrationClass(array $sql, string $dir, SymfonyStyle $io): void
    {
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $version = 'Version' . date('YmdHis');
        $filename = rtrim($dir, '/') . '/' . $version . '.php';

        $content = $this->buildMigrationClass($version, $sql);

        file_put_contents($filename, $content);
        $io->success("Doctrine migration written to: {$filename}");
    }

    /**
     * @param list<string> $sql
     */
    private function buildMigrationClass(string $version, array $sql): string
    {
        $factory = new BuilderFactory();

        // getDescription()
        $getDescription = $factory->method('getDescription')
            ->makePublic()
            ->setReturnType('string')
            ->addStmt(new Node\Stmt\Return_(new Node\Scalar\String_('Generated by Indoctrinate')))
            ->getNode();

        // up(): one $this->addSql('...') call per statement, or a comment if empty
        $upStmts = $this->buildSqlMethodStmts($factory, $sql, '// No SQL captured.');

        $up = $factory->method('up')
            ->makePublic()
            ->addParam($factory->param('schema')->setType('Schema'))
            ->setReturnType('void')
            ->addStmts($upStmts)
            ->getNode();

        // down(): informational comment only
        $downNop = new Node\Stmt\Nop();
        $downNop->setAttribute('comments', [
            new \PhpParser\Comment('// No automatic down migration — restore from a backup if needed.'),
        ]);

        $down = $factory->method('down')
            ->makePublic()
            ->addParam($factory->param('schema')->setType('Schema'))
            ->setReturnType('void')
            ->addStmt($downNop)
            ->getNode();

        $classNode = $factory->class($version)
            ->makeFinal()
            ->extend('AbstractMigration')
            ->addStmt($getDescription)
            ->addStmt($up)
            ->addStmt($down)
            ->getNode();

        $nsNode = $factory->namespace('DoctrineMigrations')
            ->addStmt($factory->use('Doctrine\\DBAL\\Schema\\Schema'))
            ->addStmt($factory->use('Doctrine\\DBAL\\Migrations\\AbstractMigration'))
            ->addStmt($classNode)
            ->getNode();

        $declare = new Node\Stmt\Declare_([
            new Node\Stmt\DeclareDeclare(
                new Node\Identifier('strict_types'),
                new Node\Scalar\LNumber(1)
            ),
        ]);

        return (new Standard([
            'shortArraySyntax' => true,
        ]))->prettyPrintFile([$declare, $nsNode]);
    }

    /**
     * Build the statement list for up() / down().
     *
     * @param list<string> $sql
     * @return list<Node\Stmt>
     */
    private function buildSqlMethodStmts(BuilderFactory $factory, array $sql, string $emptyComment): array
    {
        if ($sql === []) {
            $nop = new Node\Stmt\Nop();
            $nop->setAttribute('comments', [new \PhpParser\Comment($emptyComment)]);
            return [$nop];
        }

        $stmts = [];
        foreach ($sql as $statement) {
            $stmts[] = new Node\Stmt\Expression(
                new Node\Expr\MethodCall(
                    new Node\Expr\Variable('this'),
                    'addSql',
                    [new Node\Arg(new Node\Scalar\String_($statement))]
                )
            );
        }

        return $stmts;
    }
}
