<?php

declare(strict_types=1);

namespace Indoctrinate\Command;

use Indoctrinate\Rule\Contract\BreaksExpandContractPatternInterface;
use Indoctrinate\Rule\Contract\RuleInterface;
use Indoctrinate\Set\Contract\SetInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Finder\Finder;

class GenerateDocsCommand extends Command
{
    protected static $defaultName = 'docs';

    protected function configure(): void
    {
        $this
            ->setDescription('Generates RULES.md and per-rule pages documenting all available rules and sets')
            ->addOption('output', 'o', InputOption::VALUE_REQUIRED, 'Output file path', 'RULES.md');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outPath = (string) $input->getOption('output');

        $srcDir = $this->findSrcDir();
        if ($srcDir === null) {
            $io->error('Could not locate src/ directory.');
            return Command::FAILURE;
        }

        $rules = $this->discoverClasses($srcDir . '/Rule', 'Indoctrinate\\Rule', RuleInterface::class);
        $sets = $this->discoverClasses($srcDir . '/Set', 'Indoctrinate\\Set', SetInterface::class);

        usort($rules, fn ($a, $b) => [$a::getDriver(), $a::getCategory(), $a::getName()] <=> [$b::getDriver(), $b::getCategory(), $b::getName()]);
        usort($sets, fn ($a, $b) => $a->getName() <=> $b->getName());

        $rulesDir = rtrim(dirname($outPath), '/') . '/rules';
        if (! is_dir($rulesDir)) {
            mkdir($rulesDir, 0755, true);
        }

        file_put_contents($outPath, $this->renderIndex($rules, $sets));

        foreach ($rules as $rule) {
            $pagePath = $rulesDir . '/' . $rule::getName() . '.md';
            file_put_contents($pagePath, $this->renderRulePage($rule));
        }

        $io->success(sprintf('Written to %s and %d rule pages in %s/', $outPath, count($rules), $rulesDir));
        return Command::SUCCESS;
    }

    private function findSrcDir(): ?string
    {
        $candidates = [
            __DIR__ . '/../',
            getcwd() . '/src',
        ];
        foreach ($candidates as $candidate) {
            $real = realpath($candidate);
            if ($real !== false && is_dir($real)) {
                return rtrim($real, '/');
            }
        }
        return null;
    }

    /**
     * @template T of object
     * @param class-string<T> $interface
     * @return list<T>
     */
    private function discoverClasses(string $dir, string $baseNamespace, string $interface): array
    {
        if (! is_dir($dir)) {
            return [];
        }

        $finder = (new Finder())
            ->files()
            ->in($dir)
            ->name('*.php')
            ->notPath('Contract')
            ->notPath('Constraint');

        $instances = [];

        foreach ($finder as $file) {
            $relative = str_replace(['/', '.php'], ['\\', ''], $file->getRelativePathname());
            $fqcn = $baseNamespace . '\\' . $relative;

            if (! class_exists($fqcn)) {
                continue;
            }

            $ref = new \ReflectionClass($fqcn);
            if ($ref->isAbstract() || $ref->isInterface() || ! $ref->implementsInterface($interface)) {
                continue;
            }

            $instances[] = $ref->newInstanceWithoutConstructor();
        }

        return $instances;
    }

    /**
     * @param list<RuleInterface> $rules
     * @param list<SetInterface> $sets
     */
    private function renderIndex(array $rules, array $sets): string
    {
        $lines = [];

        $lines[] = '# Available Rules & Sets';
        $lines[] = '';
        $lines[] = '> Auto-generated by `php bin/indoctrinate docs`. Do not edit manually.';
        $lines[] = '';

        // ── Sets ──────────────────────────────────────────────────────────────
        $lines[] = '## Sets';
        $lines[] = '';
        $lines[] = 'A set is a curated group of rules that run together. Register a set in `indoctrinate.php` under `$config->sets([...])`.';
        $lines[] = '';

        foreach ($sets as $set) {
            $lines[] = sprintf('### `%s`', $set->getName());
            $lines[] = '';
            $lines[] = $set->getDescription();
            $lines[] = '';
            $lines[] = '**Rules included:**';
            $lines[] = '';
            foreach ($set->getRules() as $ruleClass) {
                $ecNote = is_a($ruleClass, BreaksExpandContractPatternInterface::class, true)
                    ? ' ⚠ *modifies in-place, does not follow Expand/Contract*'
                    : '';
                $lines[] = sprintf(
                    '- [`%s`](rules/%s.md) — %s%s',
                    $ruleClass::getName(),
                    $ruleClass::getName(),
                    $ruleClass::getDescription(),
                    $ecNote
                );
            }
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';
        }

        // ── Rules ─────────────────────────────────────────────────────────────
        $lines[] = '## Rules';
        $lines[] = '';
        $lines[] = 'Individual rules can be registered in `indoctrinate.php` under `$config->rules([...])`.';
        $lines[] = '';

        /** @var array<string, array<string, RuleInterface[]>> $byDriverCategory */
        $byDriverCategory = [];
        foreach ($rules as $rule) {
            $byDriverCategory[$rule::getDriver()][$rule::getCategory()][] = $rule;
        }

        foreach ($byDriverCategory as $driver => $categories) {
            $lines[] = sprintf('### %s', strtoupper($driver));
            $lines[] = '';

            foreach ($categories as $category => $categoryRules) {
                $lines[] = sprintf('#### %s', $category);
                $lines[] = '';

                foreach ($categoryRules as $rule) {
                    $ec = ($rule instanceof BreaksExpandContractPatternInterface) ? '⚠ Breaks E/C · ' : '';
                    $destructive = $rule::isDestructive() ? 'Destructive · ' : '';
                    $lines[] = sprintf(
                        '- [`%s`](rules/%s.md) — %s%s%s',
                        $rule::getName(),
                        $rule::getName(),
                        $destructive,
                        $ec,
                        $rule::getDescription()
                    );
                }

                $lines[] = '';
            }
        }

        return implode("\n", $lines);
    }

    private function renderRulePage(RuleInterface $rule): string
    {
        $lines = [];

        $lines[] = sprintf('# `%s`', $rule::getName());
        $lines[] = '';
        $lines[] = sprintf('> Auto-generated by `php bin/indoctrinate docs`. Do not edit manually.');
        $lines[] = '';

        $ec = ($rule instanceof BreaksExpandContractPatternInterface) ? '⚠ Breaks' : 'Safe';
        $lines[] = sprintf(
            '**Driver:** %s · **Category:** %s · **Destructive:** %s · **Expand/Contract:** %s',
            strtoupper($rule::getDriver()),
            $rule::getCategory(),
            $rule::isDestructive() ? 'Yes' : 'No',
            $ec
        );
        $lines[] = '';
        $lines[] = $rule::getDescription();
        $lines[] = '';

        $constraintClass = $rule::getConstraintClass();

        if ($constraintClass === null) {
            $lines[] = '*This rule has no constraint class — it takes no configuration.*';
            return implode("\n", $lines);
        }

        $ref = new \ReflectionClass($constraintClass);
        $lines[] = sprintf('## Constraint: `%s`', $ref->getShortName());
        $lines[] = '';
        $lines[] = sprintf(
            'Pass an instance of `%s` when registering this rule:',
            $ref->getShortName()
        );
        $lines[] = '';
        $ruleShortName = (new \ReflectionClass($rule))->getShortName();
        $lines[] = '```php';
        $lines[] = sprintf('$config->rules([%s::class => new %s(', $ruleShortName, $ref->getShortName());
        $lines[] = '    // see arguments below';
        $lines[] = ')]);';
        $lines[] = '```';
        $lines[] = '';

        $ctor = $ref->getConstructor();

        if ($ctor === null || count($ctor->getParameters()) === 0) {
            $lines[] = '*This constraint takes no arguments.*';
            return implode("\n", $lines);
        }

        $lines[] = '### Arguments';
        $lines[] = '';
        $lines[] = '| Argument | Type | Default |';
        $lines[] = '|----------|------|---------|';

        foreach ($ctor->getParameters() as $param) {
            $type = $param->hasType() ? (string) $param->getType() : 'mixed';
            $name = '$' . $param->getName();
            $default = $param->isOptional() ? $this->formatDefaultValue($param->getDefaultValue()) : '*(required)*';
            $lines[] = sprintf('| `%s` | `%s` | %s |', $name, $type, $default);
        }

        return implode("\n", $lines);
    }

    /**
     * @param mixed $value
     */
    private function formatDefaultValue($value): string
    {
        if ($value === null) {
            return '`null`';
        }
        if (is_bool($value)) {
            return $value ? '`true`' : '`false`';
        }
        if (is_int($value) || is_float($value)) {
            return sprintf('`%s`', $value);
        }
        if (is_string($value)) {
            return sprintf("`'%s'`", $value);
        }
        if (is_array($value)) {
            if (empty($value)) {
                return '`[]`';
            }
            $items = array_map(function ($v) {
                return is_string($v) ? "'{$v}'" : var_export($v, true);
            }, $value);
            return sprintf('`[%s]`', implode(', ', $items));
        }
        return sprintf('`%s`', var_export($value, true));
    }
}
