<?php

declare(strict_types=1);

namespace Indoctrinate\Command;

use Indoctrinate\Rule\Contract\RuleInterface;
use Indoctrinate\Set\Contract\SetInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Finder\Finder;

class GenerateDocsCommand extends Command
{
    protected static $defaultName = 'docs';

    protected function configure(): void
    {
        $this
            ->setDescription('Generates RULES.md documenting all available rules and sets')
            ->addOption('output', 'o', InputOption::VALUE_REQUIRED, 'Output file path', 'RULES.md');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outPath = (string) $input->getOption('output');

        $srcDir = $this->findSrcDir();
        if ($srcDir === null) {
            $io->error('Could not locate src/ directory.');
            return Command::FAILURE;
        }

        $rules = $this->discoverClasses($srcDir . '/Rule', 'Indoctrinate\\Rule', RuleInterface::class);
        $sets  = $this->discoverClasses($srcDir . '/Set',  'Indoctrinate\\Set',  SetInterface::class);

        usort($rules, fn ($a, $b) => [$a::getDriver(), $a::getCategory(), $a::getName()] <=> [$b::getDriver(), $b::getCategory(), $b::getName()]);
        usort($sets, fn ($a, $b) => $a->getName() <=> $b->getName());

        $md = $this->render($rules, $sets);

        file_put_contents($outPath, $md);

        $io->success("Written to {$outPath}");
        return Command::SUCCESS;
    }

    private function findSrcDir(): ?string
    {
        $candidates = [
            __DIR__ . '/../',
            getcwd() . '/src',
        ];
        foreach ($candidates as $candidate) {
            $real = realpath($candidate);
            if ($real !== false && is_dir($real)) {
                return rtrim($real, '/');
            }
        }
        return null;
    }

    /**
     * @template T of object
     * @param class-string<T> $interface
     * @return list<T>
     */
    private function discoverClasses(string $dir, string $baseNamespace, string $interface): array
    {
        if (!is_dir($dir)) {
            return [];
        }

        $finder = (new Finder())
            ->files()
            ->in($dir)
            ->name('*.php')
            ->notPath('Contract')
            ->notPath('Constraint');

        $instances = [];

        foreach ($finder as $file) {
            $relative = str_replace(['/', '.php'], ['\\', ''], $file->getRelativePathname());
            $fqcn = $baseNamespace . '\\' . $relative;

            if (!class_exists($fqcn)) {
                continue;
            }

            $ref = new \ReflectionClass($fqcn);
            if ($ref->isAbstract() || $ref->isInterface() || !$ref->implementsInterface($interface)) {
                continue;
            }

            $instances[] = $ref->newInstanceWithoutConstructor();
        }

        return $instances;
    }

    /**
     * @param list<RuleInterface> $rules
     * @param list<SetInterface> $sets
     */
    private function render(array $rules, array $sets): string
    {
        $lines = [];

        $lines[] = '# Available Rules & Sets';
        $lines[] = '';
        $lines[] = '> Auto-generated by `php bin/indoctrinate docs`. Do not edit manually.';
        $lines[] = '';

        // ── Sets ──────────────────────────────────────────────────────────────
        $lines[] = '## Sets';
        $lines[] = '';
        $lines[] = 'A set is a curated group of rules that run together. Register a set in `indoctrinate.php` under `$config->sets([...])`.';
        $lines[] = '';

        foreach ($sets as $set) {
            $lines[] = sprintf('### `%s`', $set->getName());
            $lines[] = '';
            $lines[] = $set->getDescription();
            $lines[] = '';
            $lines[] = '**Rules included:**';
            $lines[] = '';
            foreach ($set->getRules() as $ruleClass) {
                $lines[] = sprintf('- `%s` — %s', $ruleClass::getName(), $ruleClass::getDescription());
            }
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';
        }

        // ── Rules ─────────────────────────────────────────────────────────────
        $lines[] = '## Rules';
        $lines[] = '';
        $lines[] = 'Individual rules can be registered in `indoctrinate.php` under `$config->rules([...])`.';
        $lines[] = '';

        /** @var array<string, array<string, RuleInterface[]>> $byDriverCategory */
        $byDriverCategory = [];
        foreach ($rules as $rule) {
            $byDriverCategory[$rule::getDriver()][$rule::getCategory()][] = $rule;
        }

        foreach ($byDriverCategory as $driver => $categories) {
            $lines[] = sprintf('### %s', strtoupper($driver));
            $lines[] = '';

            foreach ($categories as $category => $categoryRules) {
                $lines[] = sprintf('#### %s', $category);
                $lines[] = '';
                $lines[] = '| Rule | Destructive | Description |';
                $lines[] = '|------|-------------|-------------|';

                foreach ($categoryRules as $rule) {
                    $destructive = $rule::isDestructive() ? 'Yes' : 'No';
                    $lines[] = sprintf(
                        '| `%s` | %s | %s |',
                        $rule::getName(),
                        $destructive,
                        $rule::getDescription()
                    );
                }

                $lines[] = '';
            }
        }

        return implode("\n", $lines);
    }
}
