<?php

declare(strict_types=1);

namespace IndoctrinateTest\Service;

use Indoctrinate\Service\ArtifactWriter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\Console\Style\SymfonyStyle;

final class ArtifactWriterTest extends TestCase
{
    private ArtifactWriter $writer;

    private SymfonyStyle $io;

    private string $tempDir;

    protected function setUp(): void
    {
        $this->writer = new ArtifactWriter();
        $this->io = new SymfonyStyle(new ArrayInput([]), new BufferedOutput());
        $this->tempDir = sys_get_temp_dir() . '/indoctrinate_writer_test_' . uniqid();
        mkdir($this->tempDir, 0755, true);
    }

    protected function tearDown(): void
    {
        $this->removeDir($this->tempDir);
    }

    // ── writeSqlDump ──────────────────────────────────────────────────────────

    public function testSqlDumpWritesHeaderAndStatements(): void
    {
        $path = $this->tempDir . '/dump.sql';
        $this->writer->writeSqlDump(
            ['ALTER TABLE users ADD COLUMN `status` VARCHAR(50)', 'CREATE INDEX idx ON users (status)'],
            $path,
            $this->io
        );

        self::assertFileExists($path);
        $content = file_get_contents($path);
        self::assertStringContainsString('-- Generated by Indoctrinate on', $content);
        self::assertStringContainsString('ALTER TABLE users ADD COLUMN `status` VARCHAR(50);', $content);
        self::assertStringContainsString('CREATE INDEX idx ON users (status);', $content);
    }

    public function testSqlDumpCreatesFileForEmptyStatements(): void
    {
        $path = $this->tempDir . '/empty.sql';
        $this->writer->writeSqlDump([], $path, $this->io);

        self::assertFileExists($path);
        self::assertStringContainsString('-- Generated by Indoctrinate on', file_get_contents($path));
    }

    public function testSqlDumpAppendsTrailingSemicolon(): void
    {
        $path = $this->tempDir . '/semi.sql';
        // Statement already stripped of semicolons by the command — writer adds them back
        $this->writer->writeSqlDump(['ALTER TABLE foo DROP COLUMN bar'], $path, $this->io);

        self::assertStringContainsString('ALTER TABLE foo DROP COLUMN bar;', file_get_contents($path));
    }

    // ── writeMigrationClass ───────────────────────────────────────────────────

    public function testMigrationClassCreatesDirectory(): void
    {
        $dir = $this->tempDir . '/migrations/sub';
        $this->writer->writeMigrationClass(['ALTER TABLE t ADD COLUMN x INT'], $dir, $this->io);

        self::assertDirectoryExists($dir);
    }

    public function testMigrationClassWritesValidPhp(): void
    {
        $this->writer->writeMigrationClass(
            ['ALTER TABLE users MODIFY COLUMN email VARCHAR(320)'],
            $this->tempDir,
            $this->io
        );

        $files = glob($this->tempDir . '/Version*.php');
        self::assertCount(1, $files);

        $content = file_get_contents($files[0]);
        self::assertStringContainsString('extends AbstractMigration', $content);
        self::assertStringContainsString('public function up(', $content);
        self::assertStringContainsString('public function down(', $content);
        self::assertStringContainsString('$this->addSql(', $content);
        self::assertStringContainsString('ALTER TABLE users MODIFY COLUMN email VARCHAR(320)', $content);
    }

    public function testMigrationClassEscapesSingleQuotes(): void
    {
        $this->writer->writeMigrationClass(
            ["ALTER TABLE t ALTER COLUMN x SET DEFAULT 'value'"],
            $this->tempDir,
            $this->io
        );

        $files = glob($this->tempDir . '/Version*.php');
        $content = file_get_contents($files[0]);
        // Single quotes inside the SQL must be escaped to avoid breaking the PHP string
        self::assertStringContainsString("\\'value\\'", $content);
    }

    public function testMigrationClassEmptySqlWritesComment(): void
    {
        $this->writer->writeMigrationClass([], $this->tempDir, $this->io);

        $files = glob($this->tempDir . '/Version*.php');
        $content = file_get_contents($files[0]);
        self::assertStringContainsString('// No SQL captured.', $content);
    }

    public function testMigrationFileNameFollowsVersionPattern(): void
    {
        $this->writer->writeMigrationClass(['ALTER TABLE t ADD COLUMN x INT'], $this->tempDir, $this->io);

        $files = glob($this->tempDir . '/Version*.php');
        self::assertCount(1, $files);
        self::assertMatchesRegularExpression('~Version\d{14}\.php$~', basename($files[0]));
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    private function removeDir(string $dir): void
    {
        if (! is_dir($dir)) {
            return;
        }
        foreach (scandir($dir) as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            $path = $dir . '/' . $entry;
            is_dir($path) ? $this->removeDir($path) : unlink($path);
        }
        rmdir($dir);
    }
}
